### ISSUE TITLE
Generate yaml files for different environments

### ISSUE THREAD

**Issue by borramTAS** [eclipse/jkube#1218]
### Description

I need to generate different yaml files for different environments, not only for the same environment but also different configurations for the same environment. It would be useful to have a basic templating system to be used for the different targets and specific modifications for the different combinations, it could use a system based on directories, one `commons` and one for each target (environment or deployment) for example.

### Related to

- https://gitter.im/eclipse/jkube?at=618245467db1e3753e7ba861

**Comment by manusa** [comment]
If I understand correctly, this issue is requesting the possibility to apply more than one environment configuration.

Considering the following directory structure
```
src/main/jkube/dev
src/main/jkube/prod
src/main/jkube/common
```

Being able to provide `<jkube.environment>common,dev</jkube.environment>` or `<jkube.environment>common,prod</jkube.environment>` as a valid configuration that would account for fragments in the listed directories would solve your issue.

**Comment by borramTAS** [comment]
> If I understand correctly, this issue is requesting the possibility to apply more than one environment configuration.

Basically yes.

> Being able to provide <jkube.environment>common,dev</jkube.environment> or <jkube.environment>common,prod</jkube.environment> as a valid configuration that would account for fragments in the listed directories would solve your issue.

I would say yes, it would solve my issue.

**Comment by borramTAS** [comment]
Very good news, I will test it as soon as it is available, thank you very much!

**Comment by borramTAS** [comment]
I refactored my project and now it works like a charm, I'll try a more complex scenario.

**Comment by manusa** [comment]
> I refactored my project and now it works like a charm, I'll try a more complex scenario.

Great news, thanks for the feedback!
