### ISSUE TITLE
HealthCheckConfigTest : Use assertThrows instead of `@Test(expected = IllegalArgumentException.class)` annotation

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#1374]
### Description
Right now we're using this `expected` annotation for verifying exception thrown in test. We should use `Assert.assertThrows` instead since it's move flexible and level returns thrown exception's object which can be asserted further if necessary

https://github.com/eclipse/jkube/blob/b45facd5b3dd25a31850d2f38b96c73edf66b83a/jkube-kit/config/image/src/test/java/org/eclipse/jkube/kit/config/image/build/HealthCheckConfigTest.java#L95-L154

- [x] Remove `expected` annotation from test and use `assertThrows`
- [ ] Try to check if these can be converted into a parameterized test

**Comment by Devamparikh** [comment]
Hey Can I pick this up? I want to contribute.

**Comment by Devamparikh** [comment]
Check out last PR #1399 for this issue.

**Comment by manusa** [comment]
> Check out last PR #1399 for this issue.

Hi @Devamparikh ,
If you check the issue in GitHub's web interface, you'll notice that the full activity for your PRs has been logged here. This is because you added proper descriptions and messages to your PRs (and even your git commits).
Unless we voluntarily opted-out, maintainers of this repo get notified about all of this. Comments such as this one are not really needed, unless a long time has passed, and maybe we missed something. Otherwise, they are redundant and only help to flood our inboxes.
