### ISSUE TITLE
Provide JKube Bom

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#187]
To ease dependency management using Maven or Gradle, It would be nice if a Bill of Materials POM could be  provided under the org.eclipse.jkube:jkube-bom:1.0.0 Maven coordinates.

**Comment by manusa** [comment]
How does this compare to https://github.com/eclipse/jkube/blob/master/jkube-kit/parent/pom.xml ?

**Comment by rohanKanojia** [comment]
Umm, Not sure if I understand your question correctly. Are you saying we have something equivalent already? We have something similar in Kubernetes Client also for all dependencies: https://github.com/fabric8io/kubernetes-client/blob/master/pom.xml#L635

**Comment by manusa** [comment]
That looks like a BOM generator based on sundr.io.

BOM's are used as a dependency management system so that dependencies for all modules are consistent and defined in a single place. This is what our jkube-kit-parent module does for jkube-kit specific dependencies, and also our jkube root pom does for dependencies used in jkube-kit **and** maven plugins.

The point of BOMs is to not need to specify dependency artifact version in the modules where they are effectively used (this way you also prevent from using different versions of a dependency across modules).

We can change the *-maven-plugin to make use of this parent so then we can get rid of the `<version>${jkube.kit.version}</version>`. This is one of the first tasks I started in the project when working on the JKube-kit refactor and maven-enforcer plugin, most of the poms there should already be streamlined. This task is missing to be completed for the plugins.

```xml
    <!-- ... -->
    <dependencies>
        <dependency>
            <groupId>org.eclipse.jkube</groupId>
            <artifactId>jkube-kit-parent</artifactId>
            <version>${jkube.kit.version}</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
        <!-- ... The rest of dependencies can now be referenced without <version> tags ... -->
    </dependencies>
    <!-- ... -->
```

**Comment by manusa** [comment]
Closing this issue since it's unclear and we already have the parent pom that serves as BOM.
