### ISSUE TITLE
Update Migration guide with latest version of JKube

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#200]
I was looking at migration guide[0] and it still seems to be having old `artifactId` for plugins. We should update it with correct `artifactId` and version

[0] https://www.eclipse.org/jkube/docs/migration-guide/

**Comment by manusa** [comment]
We need to create a list of items that must be updated whenever we perform a release, besides the items in the website.

Regarding the website, migration guide may be scripted so that version is taken from the latest release (similar approach to what we have in the Documentation which will also publish the docs for the latest Maven Central released version)

**Comment by manusa** [comment]
After #195 Migration guide should focus on how (easy) is to use our new goal to migrate a project from FMP to Eclipse JKube.
