### ISSUE TITLE
Build fails with "-Dorg.slf4j.simpleLogger.defaultLogLevel=trace" option

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#2000]
Mirror of [ENTESB-20503](https://issues.redhat.com/browse/ENTESB-20503)

Minor relation with #1950 

Test repository:

https://github.com/luigidemasi/spring-boot-camel-config/tree/omp-with-trace

Regular build works, build with log tracing fails.

**Comment by luigidemasi** [comment]
This is the stacktrace of the exception:

![image](https://user-images.githubusercontent.com/5583341/212345035-681535e2-6f72-4086-a0fa-0d614d521daa.png)


The difference between the successful build with trace disabled  and the failing one with trace enabled is that the call is performed inside the logging interceptor.

**Comment by manusa** [comment]
Hi @shawnkins
This might relate to some other weird behaviors we've seen with the Interceptors and the HTTP request handling.

**Comment by shawkins** [comment]
@manusa the only thing I'm aware of related to this is the HttpClient.Builder.forStreaming method - it modifies the logging interceptor so that it doesn't interfere https://github.com/fabric8io/kubernetes-client/blob/fbe8cd12ce2a5ddefb5eac89acee4623a4b85d39/httpclient-okhttp/src/main/java/io/fabric8/kubernetes/client/okhttp/OkHttpClientBuilderImpl.java#L119

However we currently only call that for http watches.  

The logging issue is probably more general now because we no longer delegate the body logic to okhttp - it will always be streaming.

**Comment by luigidemasi** [comment]
The problem is here:
https://github.com/fabric8io/kubernetes-client/blob/d6e6cc35c689f5dd1920d95a73aa77174a645f43/httpclient-okhttp/src/main/java/io/fabric8/kubernetes/client/okhttp/OkHttpRequestImpl.java#L86

The writeTo method is called twice, once for logging, the second to write the request on the wire. The try-with-resources closes the stream at the end of the first method invocation, so the second time is invoked it raises the "IOException: Stream closed"

https://github.com/square/okhttp/issues/3643#issuecomment-36654725


Removing the try-with-resources makes it working as expected, and for short execution like in a maven plugin is ok, for a long running process leaving a buffer opened could be a problem.

**Comment by tmielke** [comment]
I see this ticket had some momentum back in Jan but since then work seems to be stalled.
Is there any time frame for this fix? We have a customer affected by it (even though not critically) as per [ENTESB-20503](https://issues.redhat.com/browse/ENTESB-20503).

**Comment by manusa** [comment]
Once we update JKube to Fabric8 Kubernetes Client v6.6.0 (just released), this issue should be mitigated.
