### ISSUE TITLE
oc:build or k8s:build should warn the user that he may have forgotten to run a build or package

### ISSUE THREAD

**Issue by sunix** [eclipse/jkube#2070]
### Component

None

### Is your enhancement related to a problem? Please describe

Context: User using an openshift cluster to deploy his development app.
1. user types `mvn package oc:build oc:resource oc:apply` to deploy the application
2. user is making modifications
3. user types `mvn oc:build oc:resource oc:apply` to deploy the app (missing `package`)
4. user is not seeing any changes in the deploy app

### Describe the solution you'd like

If the user forgets about running `mvn package` prior to `oc:build`, JKube should notify the user that he may have forgotten to run `mvn package` .

### Subtasks
- [ ] webapp generator: https://github.com/eclipse/jkube/pull/2244
- [ ] investigate if it is possible to implement it in a more generic fashion
- [ ] quarkus generator
- [ ] ....

**Comment by rohanKanojia** [comment]
This looks related to https://github.com/eclipse/jkube/issues/1328 . There fix was done only in WebAppGenerator

**Comment by fMurugi** [comment]
Hello I am beginner interested in contributing to this project .Are there beginner issues for one to try?
Help will be really appreciated.

**Comment by ShivangMishra** [comment]
@rohanKanojia @sunix even though this issue is related to #1328, we can't use the same approach because in #1328 we could simply check if the final output artefact was null ( JKubeProjectUtil.getFinalOutputArtifact(getProject()) ), but here the artefact would be already present as the user ran mvn package once already. 
In #2070 we basically want to check whether the user ran the plugin in package phase (mvn package oc:build oc:resource oc:apply) or directly (mvn oc:build oc:resource oc:appl).

I think we can use execution.getLifecyclePhase() in our Mojo to check this. We can then warn the user that they forgot to run mvn package...
<Or maybe we can set our plugin to run in package phase if no phase was specified.>

What do you think ?

**Comment by rohanKanojia** [comment]
I haven't checked code but I think we need to make changes to all framework generators for this or maybe modify it's parent [JavaExecGenerator](https://github.com/eclipse/jkube/blob/master/jkube-kit/generator/java-exec/src/main/java/org/eclipse/jkube/generator/javaexec/JavaExecGenerator.java)

Do you want to work on this issue?

**Comment by ShivangMishra** [comment]
> I haven't checked code but I think we need to make changes to all framework generators for this or maybe modify it's parent [JavaExecGenerator](https://github.com/eclipse/jkube/blob/master/jkube-kit/generator/java-exec/src/main/java/org/eclipse/jkube/generator/javaexec/JavaExecGenerator.java)
> 
> Do you want to work on this issue?

Yes I want to work on it

**Comment by ShivangMishra** [comment]
@sunix  I cannot edit the checkboxes in the PR description. 
So, I'm stating here and in the doc sheet. 
I have implemented a generic fix for this issue for all generators in #2244.
