### ISSUE TITLE
Document the usage of SNAPSHOTs

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#2254]
### Description

After #2253, SNAPSHOTs are now being published nightly:
- https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/jkube/
- https://ci.eclipse.org/jkube/job/ReleasePipelines/job/ReleaseSnapshots/

We need to add documentation for users to learn how to use these SNAPSHOTs. Maybe also tune the Quickstarts or provide a specific quickstart for this purpose (replacement of #2069)

**Comment by rohanKanojia** [comment]
Example documentation: https://github.com/checkstyle/checkstyle/wiki/How-to-use-Checkstyle-snapshot-artifacts

**Comment by manusa** [comment]
> Example documentation: https://github.com/checkstyle/checkstyle/wiki/How-to-use-Checkstyle-snapshot-artifacts

Only the `pluginRepository` section applies. The plugin dependency setup is missing.

**Comment by Prafful-Rastogi** [comment]
Hi @manusa I would like to take this issue but I am contributing for the first time in open source. Can you please assign this to me and help me get started?

**Comment by rohanKanojia** [comment]
@Prafful-Rastogi : Hello, thanks for showing interest in contributing to Eclipse JKube. You need to follow these steps to contribute:

1. In order to contribute to Eclipse, you would need to create an [Eclipse Account](https://accounts.eclipse.org/) and Sign [Eclipse Contributor Agreement](https://accounts.eclipse.org/user/login?destination=user/eca).
2. Configure your Git Username  `git config --global user.name "John Doe"`
3. Configure your Git email `git config --global user.email johndoe@example.com`
4. Fork JKube repository on Github 
5. Clone JKube repository `git@github.com:eclipse/jkube.git`
6. Add git remote for your fork `git remote add Prafful-Rastogi git@github.com:Prafful-Rastogi/jkube.git`
7. Create new branch for this task `git checkout -b pr/issue2254`
8. Add a file named USING-SNAPSHOT-ARTIFACTS.md in repository with the following content 
```diff
+# How to use Eclipse JKube snapshot artifacts?
+
+Artifacts are hosted at [JKube's Sonatype Snapshot repository](https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/jkube/)
+
+Our [Jenkins Snapshot release pipeline](https://ci.eclipse.org/jkube/job/ReleasePipelines/job/ReleaseSnapshots/) updates SNAPSHOT artifacts every night.
+
+
+## Using SNAPSHOTs in Maven Project
+In order to use these artifacts, update your `pom.xml` with these:
+
+```xml
+<pluginRepositories>
+  <pluginRepository>
+    <id>oss.sonatype.org</id>
+    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
+    <snapshots>
+      <enabled>true</enabled>
+      <updatePolicy>always</updatePolicy>
+    </snapshots>
+  </pluginRepository>
+</pluginRepositories>
+```
+
+You'd also need to update version of the plugin you're using to use a SNAPSHOT version instead of a stable version. Here is an example:
+
+```xml
+<properties>
+    <jkube.version>x.yz-SNAPSHOT</jkube.version>
+</properties>
+
+<build>
+    <plugins>
+        <plugin>
+            <groupId>org.eclipse.jkube</groupId>
+            <artifactId>kubernetes-maven-plugin</artifactId>
+            <version>${jkube.version}</version>
+        </plugin>
+    </plugins>
+</build>
+```
+
+## Using SNAPSHOTS in Gradle project
+
+In order to use these artifacts in Gradle project, update your `settings.gradle` pluginManagement section like this:
+
+```groovy
+pluginManagement {
+    repositories {
+        maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
+    }
+}
+```
+
+You'd also need to update version of the plugin you're using to use a SNAPSHOT version instead of a stable version. Here is an example:
+
+```groovy
+plugins {
+    id "org.eclipse.jkube.openshift" version "x.yz-SNAPSHOT"
+    id "org.eclipse.jkube.kubernetes" version "x.yz-SNAPSHOT"
+}
+```
```
10. Add entry to README table of contents for this file:
```diff
 - [Rebranding Notice](#rebranding-notice--loudspeaker-)
 - [Contributing](https://www.eclipse.org/jkube/contributing/)
+- [How to use Eclipse JKube snapshot artifacts?](./USING-JKUBE-SNAPSHOTS.md)
 - [Add your organization to ADOPTERS](./ADOPTERS.md)
 - [FAQs](https://www.eclipse.org/jkube/docs/kubernetes-maven-plugin/#faq)
```
11. Add your changes to git index `git add USING-SNAPSHOT-ARTIFACTS.md README.md`
12. Commit your changes `git commit --signoff -m "doc : Add documentation for using jkube snapshots"`
13. Push your changes to your fork `git push Prafful-Rastogi  pr/issue2254`
14. Create pull request from GitHub interface

If you've any problems in following these steps, please ping me on our [Gitter channel](https://app.gitter.im/#/room/#eclipse_jkube:gitter.im)

**Comment by Prafful-Rastogi** [comment]
Hi @rohanKanojia, I have made a pull request and would appreciate to get a feed back. Thanks for your support.
