### ISSUE TITLE
SpringBoot Layered Jar not properly reusing cache

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#2393]
## Description

The current approach to prepare the layers for Spring Boot Layered Jar nested generator is not working OK.

The dependency layers don't preserve the original creation date of the jar dependencies. This causes the layer digest to change from build to build. Hence, the layers can't be reused from their cached digest id.

> [!NOTE]
> It seems that when the assembly is prepared, the timestamps for the files are lost.

## Relates to
- #763 
- #1674 
- #2309

**Comment by rohanKanojia** [comment]
I think this issue is not just specific to SpringBoot. I think none of the container images generated by the generators are able to utilize the docker cache. We add some labels to container image in BaseGenerator
https://github.com/eclipse/jkube/blob/10051905f838d2af69002cc083fec6ab5a314b63/jkube-kit/generator/api/src/main/java/org/eclipse/jkube/generator/api/support/BaseGenerator.java#L259

This adds a label build date with timestamp in Dockerfile, this changes for every build even if no change is applied. This triggers rebuild of layers added below labels. 

Here is a diff of two Dockerfiles generated on two consecutive `k8s:build` with no changes:

![Screenshot_20230928_122736](https://github.com/eclipse/jkube/assets/13834498/4bdad62a-063c-4511-84a1-bcb4cfeb39c1)

We should change `org.label-schema.build-date` label to either only only date (not complete timestamp), or drop the `org.label-schema.build-date` label altogether.

**Comment by manusa** [comment]
I'm not really sure about this.
Have you verified that removing the label actually reuses the cached layers?
Is the label also added to the intermediate layers?

For Jib we're already basing the build on a constant date.
If this is the real underlying cause, then I think the best option is to just remove the label.
