### ISSUE TITLE
Buildpacks CLI (pack) downloader

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#2454]
## Description

Part of #439 

As a JKube developer, I want to be able to let JKube automatically download a Buildpacks CLI (pack) binary compatible with my platform and system architecture, so that I can invoke a consistent version of the CLI tool (see #2453).

TODO:
- Define the binary source URLs or method to infer them
- Define the target location for the downloaded binaries
- Define what happens if the downloaded binary is corrupt (recover, force update)
- Define what happens in an air-gapped environment (should we fallback to existent CLI?)

**Comment by rohanKanojia** [comment]
- **Define the binary source URLs or method to infer them**
  As agreed internally at standup meeting, we decided that binary source download URL, version and other attributes could be inferred from parent pom via properties:
  ```xml
      # BuildPack related properties in Parent Pom
    <version.cli.pack.upstream.github>v0.32.1</version.cli.pack.upstream.github>
    <download-link.cli.pack.upstream.github>https://github.com/buildpacks/pack/releases/download</download-link.cli.pack.upstream.github>
    <binary-prefix.cli.pack.upstream.github>pack</binary-prefix.cli.pack.upstream.github>
    <archive-suffix.unix.cli.pack.upstream.github>tgz</archive-suffix.unix.cli.pack.upstream.github>
    <archive-suffix.windows.cli.pack.upstream.github>zip</archive-suffix.windows.cli.pack.upstream.github>
  ```


- **Define the target location for the downloaded binaries**
  (Proposed)
  Build output directory. It would align with the behavior of maven/gradle plugins.
  
 
- **Define what happens if the downloaded binary is corrupt (recover, force update)**
  (Proposed)
  When JKube detects a pack binary already present on system, it checks whether it's in expected state by running `pack --version` command. If this command completes successfully, then binary is considered to be in a usable state; Otherwise, download is triggered.
  
- **Define what happens in an air-gapped environment (should we fallback to existent CLI?)**
  (Proposed)
  If download fails, JKube would look for pack CLI already present on machine. It would check whether it's valid or not by checking (`pack --version`) command. If previous step is successful, then we use the binary already present on User's system.
  - Shall we enforce user to have `pack` CLI only above certain version? Shall we throw error if user has `pack` CLI with old version?
