### ISSUE TITLE
oc:build does not update labels and annotations in Openshift Build resource

### ISSUE THREAD

**Issue by MimerPlusPlus** [eclipse/jkube#2500]
### Describe the bug

(As discussed with @rohanKanojia on Gitter)
jKube does not update pom version and git information in labels (_.metadata.labels.version_) and annotations (jkube.io/git-branch and kube.io/git-commit) with current information from the Maven build. Instead the information is just copied from the BuildConfig.

Tested on OpenShift 4.12 with Maven 3.9.4 and jKube 1.3.0 (from Red Hat Fuse)

### Eclipse JKube version

1.3.0

### Component

Kubernetes Maven Plugin

### Apache Maven version

other (please specify in additional context)

### Gradle version

None

### Steps to reproduce

1) Build and apply a project to OpenShift (creating a BuildConfig and a Build)
2) Update to new GitBranch and commit a new POM version.
3) Do a mvn oc:build
4) Verify that latest OpenShift Build has updated to POM version and Git commit/branch in labels and annotations.

### Expected behavior

Latest OpenShift Build should be updated with latest POM version and Git information (branch and commit key)

### Runtime

OpenShift

### Kubernetes API Server version

other (please specify in additional context)

### Environment

macOS

**Comment by manusa** [comment]
Suggested changes:
- Git issues
  - `GitEnricher` should implement `enrich` instead of `create`
  - `GitEnricherTest` should verify that the current supported Kubernetes objects get enriched (use of KubernetesListBuilder and test overall behavior)
  - `GitEnricherTest` should contain a new clause for the OpenShift build-related resources (Build, BuildConfig...)
  - `GitEnricher` should be modified to use a generic visitor instead of providing specific visitors.
- Project label
  - Doesn't update the version number (or any other project-related info) on subsequent builds.
  - `OpenShiftBuildService` might need to consider the changes in metadata (such as labels and annotations) -- evaluate possible side-effects

**Comment by rohanKanojia** [comment]
@manusa : Shall we close this issue? I had moved BuildConfig's `version` label related behavior into #2561 .
