### ISSUE TITLE
Refactor JKubeServiceHub's BuildService election mechanism

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#253]
Right now we have a really ugly way of selecting a particular `BuildService` 
https://github.com/eclipse/jkube/blob/1c916f9e76566e8d2bc0721156742bd04bf5161a/jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/JKubeServiceHub.java#L100-L110

This approach is fine for now but as we plan to increase support for multiple builds(like JIB, Buildah, Podman etc). We need to refactor this and make it generic. We can probably implement it like we're doing in case of Generators:
https://github.com/eclipse/jkube/blob/1c916f9e76566e8d2bc0721156742bd04bf5161a/kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/generator/GeneratorManager.java#L52-L60

**Comment by manusa** [comment]
I thought there was an extra-issue for this, but we probably just discussed this elsewhere because I can't find it.

In addition to the way BuildService implementations are discovered and instantiated, we need a way to automatically (in case the user doesn't provide a manual configuration `jkube.build.strategy` select a build service based on the environment where the plugin is run (maybe with a scoring system).

So, for openshift-maven-plugin, current assumption is to use s2i or in cluster Docker if specified as a build strategy. :heavy_check_mark: 

However, for kubernetes-maven-plugin, if no strategy is selected, JKube should be smart enough to select the appropriate build strategy. e.g. try with Docker, fallback to jib
