### ISSUE TITLE
ImageChangeTriggerEnricher : Replace boxed `Boolean` with primitive `boolean` type

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#2674]
### Component

JKube Kit

### Description
ImageChangeTriggerEnricher seems to be using `Boolean` fields members:
https://github.com/eclipse/jkube/blob/cc2c8a20c541c78c26f752058dc5bf334f74ff2b/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/ImageChangeTriggerEnricher.java#L39-L41

Unless it's needed, it's always better to stick to primitive types instead of boxed types. These should be replaced by `boolean`. 

There are another place in this class as well where we're using `Boolean` as method return value, we should replace it with use `boolean` return type as well:
https://github.com/eclipse/jkube/blob/cc2c8a20c541c78c26f752058dc5bf334f74ff2b/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/ImageChangeTriggerEnricher.java#L114

Same for this one:
https://github.com/eclipse/jkube/blob/cc2c8a20c541c78c26f752058dc5bf334f74ff2b/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/ImageChangeTriggerEnricher.java#L116

### Expected Behavior
Replace usage of `Boolean` private variables with `boolean`.

### Acceptance Criteria
- [x] `enableAutomaticTrigger` type is changed to `boolean`
- [x]  `enableImageChangeTrigger` type is changed to `boolean`
- [x]  `trimImageInContainerSpecFlag` type is changed to `boolean`
- [x] `isImageChangeTriggerNeeded` method return type changed to `boolean`
- [x] `enrichAll` field on line  116 type changed to `boolean`
- [x] [ImageChangeTriggerEnricherTest](https://github.com/eclipse/jkube/blob/master/jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/openshift/ImageChangeTriggerEnricherTest.java) should pass after making the abovementioned changes

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by GeHa6yKuH** [comment]
Hello, could you please assign this to me?

**Comment by GeHa6yKuH** [comment]
Could you please tell me how can I run the test under https://github.com/eclipse/jkube/blob/master/jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/openshift/ImageChangeTriggerEnricherTest.java? I have never contributed to your project and Im completely new here and when I am trying to execute the test the project just can not be built. I know that I am probably doing something wrong because it seems like the code should be tested in Kubernetes and Openshift but I have literally no Idea how to do it and unfortunatelly I did not find the answer on this question in your documentation. I got the minikube installed on my PC and I have docker with Kubernetes switched on but I don't know how to use it with your project on my local machine.  Great if you could explain it to me or provide a link which explains it, thank you!

**Comment by rohanKanojia** [comment]
@GeHa6yKuH : For the sake of this issue, just running unit tests from IntelliJ is enough

In order to set up jkube in your IDE, do this:
1. Setup Maven and java 8/11
2. Run `mvn clean install -DskipTests` (skipping tests to save time)
3. Open the project in IntelliJ as a maven project

**Comment by GeHa6yKuH** [comment]
Oh I'm sorry thank you very much!!

чт, 15 февр. 2024 г., 22:17 Rohan Kumar ***@***.***>:
