### ISSUE TITLE
Quickstarts kubernetes-maven-plugin version pinned to quickstart version

### ISSUE THREAD

**Issue by duke-arioch** [eclipse/jkube#274]
Since the quickstarts are not children of the main project, and change according to a different numbering scheme, they should not use the ${project.version} (which is their own internal project version) - to specify the version of the kubernetes maven plugin to use.

If the intent is to use the current repo kubernetes maven plugin , then the top level plugin version should be propagated down to the quickstarts by some mechanism. Otherwise, if the quickstarts are intended to use the published version from the repository, then the top level release process should also update the quickstarts to use the released version of the plugin.

**Comment by duke-arioch** [comment]
I'm going to close this for now - but maybe think about if we want to pin to snapshot version or just latest published.

**Comment by manusa** [comment]
Hi @duke-arioch 

Quickstarts should use the latest released version of Kubernetes-Mave-Plugin or OpenShift-Maven-Plugin. In some cases you'll find they reference the `SNAPSHOT` version because they simply won't work with the latest release due to a missing feature or bug.

The point of linking the plugin version to the quickstart project version is for maintenance simplicity. We have a few scripts that will change the value using [Versions Maven Plugin](https://www.mojohaus.org/versions-maven-plugin/index.html) in our release process. If you find this may be confusing we can change it and use different values for the quickstart project version and the plugin version.

**Comment by duke-arioch** [comment]
Thanks @manusa - I came to this issue because the snapshot version works great on windows 10 - the released version does not. It was a simple matter to change the version, but I didn't imagine that the quickstarts would not use the built version of the code after I built the plugins etc. It was just a surprise and I can see why you would want to tie to released version. It may make sense in this case to add a variable for the plugin version that is different from the quickstart version. I could probably argue around in circles and support either viewpoint on this matter though. Overall the tool is working well and I am happy with the results. Thanks for the efforts.
