### ISSUE TITLE
ProfileUtilTest.findProfile_whenValidProfileArg_returnsValidProfile The declared Exception exception is never thrown

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#2778]
### Description

The method [ProfileUtilTest.findProfile_whenValidProfileArg_returnsValidProfile](https://github.com/eclipse/jkube/blob/5da6068d7756784aef9569568ee80f98da97e296/jkube-kit/profile/src/test/java/org/eclipse/jkube/kit/profile/ProfileUtilTest.java#L60) declares an Exception that is never thrown.

The following line
https://github.com/eclipse/jkube/blob/5da6068d7756784aef9569568ee80f98da97e296/jkube-kit/profile/src/test/java/org/eclipse/jkube/kit/profile/ProfileUtilTest.java#L60

- [x] should be changed to:

```java
    void findProfile_whenValidProfileArg_returnsValidProfile() throws URISyntaxException {
```

### Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down::point_down::point_down::point_down::point_down::point_down::point_down:
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by Jonathanlemon** [comment]
Could I be assigned this issue @manusa ?

**Comment by rohanKanojia** [comment]
@Jonathanlemon [`first-timers-only`](https://github.com/eclipse/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Afirst-timers-only) tagged issues are created for newcomers who are contributing to the project for the first time so that they can complete legal requirements and get familiar with project.

Now that you’ve completed that step, I would advise you to look into issues tagged with [`good first issue` / `help wanted` labels](https://github.com/eclipse/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22+label%3A%22help+wanted%22) . Or maybe create some new issue if you find something that should be fixed.

**Comment by ArunErram** [comment]
can i work on these issue ?
@manusa @rohanKanojia

**Comment by manusa** [comment]
> can i work on these issue ? @manusa @rohanKanojia

See Rohan's comment:

> [first-timers-only](https://github.com/eclipse/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Afirst-timers-only) tagged issues are created for newcomers who are contributing to the project for the first time so that they can complete legal requirements and get familiar with project.

Now that you’ve completed that step, I would advise you to look into issues tagged with [good first issue / help wanted labels](https://github.com/eclipse/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22+label%3A%22help+wanted%22) . Or maybe create some new issue if you find something that should be fixed.

https://github.com/eclipse/jkube/pull/2589

**Comment by agusaar** [comment]
Hi there @manusa , is this issue solved? If not, I would like to work on it.

**Comment by agusaar** [comment]
When I try to clone the repository I get the following error:

error: unable to create file jkube-kit/build/api/src/test/resources/assembly/assembly-manager-create-docker-tar-archive/without-dockerfile-and-already-existing-file-in-assembly-gets-overwritten/jkube-generated-layer-final-artifact/maven/test-0.1.0.jar: Filename too long

Is there a chance of modifying the path to the file in order to make it shorter?

**Comment by agusaar** [comment]
Solved by settinng core.longpaths to true
