### ISSUE TITLE
JavaExecGenerator should merge system properties

### ISSUE THREAD

**Issue by jfdenise** [eclipse/jkube#384]
### Description
If a generator that extends the Java generator generates System properties (eg: overrides getExtraJavaOptions) these properties replace the one a user could have set. We would need to have them merged and only added if a user doesn't redefine them.

### Info

* Eclipse JKube version : 1.0.0

**Comment by manusa** [comment]
The situation is visible/reproducible in the Vert.x quickstart.

The [src/main/jkube/deployment.yaml](https://github.com/eclipse/jkube/blob/bc9257531cd8db493d188d7c4717734f13f357bc/quickstarts/maven/vertx/src/main/jkube/deployment.yaml#L18): Fragment contains a `JAVA_OPTIONS` environment variable entry that overrides the ones specified in the [generator](https://github.com/eclipse/jkube/blob/2a29784a27e75052767f3cc986da02c812f9dd96/jkube-kit/jkube-kit-vertx/src/main/java/org/eclipse/jkube/vertx/generator/VertxGenerator.java#L58).

```
2020-09-22T05:43:40.197938416Z INFO exec java -Xmx1500m -javaagent:/usr/share/java/jolokia-jvm-agent/jolokia-jvm.jar=config=/opt/jboss/container/jolokia/etc/jolokia.properties -XX:+UseParallelOldGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MaxMetaspaceSize=100m -XX:+ExitOnOutOfMemoryError -cp "." -jar /deployments/vertx-1.0.0.jar
```

All the extra java options get lost.

**Comment by manusa** [comment]
In order to solve the problem, we can add a `ContainerEnvJavaOptionsEnricher` that will take care of merging any `JAVA_OPTIONS` environment variable value defined in the `ImageConfiguration` with the ones from the XML configuration.

In addition, the method/logic behind [KubernetesResourceUtil#ensureHasEnv](https://github.com/eclipse/jkube/blob/fd86bc94355c6026e83d4a637139c6f1de9ebdfe/jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java#L692) should be improved so that the value is merged when taken from a fragment.
