### ISSUE TITLE
dot in repository delete the registry configuration in pom.xml

### ISSUE THREAD

**Issue by rgordill** [eclipse/jkube#523]
### Description
When using dot in repositories, the registry part is missing. Example:
```
<name>rgordill/%a:%l</name>
<registry>quay.io</registry>
```
Gives a correct images in the deployment: 
`image: quay.io/rgordill/customer-service-cache:latest`

But when using:
```
<name>ramon.gordillo/%a:%l</name>
<registry>quay.io</registry>
```
Gives a correct images in the deployment: 
`image: ramon.gordillo/customer-service-cache:latest`

### Info

* Eclipse JKube version : 1.0.2
* Maven version (`mvn -v`) : 3.6.3

* Kubernetes / Red Hat OpenShift setup and version : k8s 1.19

* If it's a bug, how to reproduce : See the reproducer project

* Sample Reproducer Project : *https://github.com/rgordill/customer-service-cache/tree/af19d20254895892ce184a672cd35364b13d4ddf*

**Comment by manusa** [comment]
Relates to: https://github.com/eclipse/jkube/issues/526

**Comment by rohanKanojia** [comment]
Quay.io Seems to allow a username with dots:
![Screenshot_20210121_192446](https://user-images.githubusercontent.com/13834498/105360812-02769700-5c1f-11eb-94ae-ed2ab414eef9.png)

However, DockerHub doesn't allow such usernames:
![Screenshot_20210121_192714](https://user-images.githubusercontent.com/13834498/105360853-11f5e000-5c1f-11eb-87b4-714aa19c7026.png)

I think this is due to an expectation in `ImageName` class that is there is a `.` or `:` in name then it's a registry:
https://github.com/eclipse/jkube/blob/ff0bbc82a1b2a9a05465a6e62a35f4184a2c7c3d/jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/ImageName.java#L145-L148

Due to this assumption, we're assuming the first one is a registry and assign it to the registry in image name here:
https://github.com/eclipse/jkube/blob/ff0bbc82a1b2a9a05465a6e62a35f4184a2c7c3d/jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/ImageName.java#L278-L283

It gets called via `ContainerHandler` during resource phase here:
https://github.com/eclipse/jkube/blob/ff0bbc82a1b2a9a05465a6e62a35f4184a2c7c3d/jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/handler/ContainerHandler.java#L70

I think we should fix this behavior since a username with dots seems to work fine with Docker.
