### ISSUE TITLE
OpenShift switchToDeployment flag

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#630]
### Description
Document the usage of the flag `jkube.build.switchToDeployment`

See why `<jkube.enricher.jkube-controller.type>Deployment</jkube.enricher.jkube-controller.type>` is not working as expected with OpenShift Maven Plugin.

See how these flags interact

**Comment by rohanKanojia** [comment]
`<jkube.enricher.jkube-controller.type>Deployment</jkube.enricher.jkube-controller.type>` is not working in openshift mode since OpenShift mode also depends on an additional condition `platformMode == PlatformMode.openshift && useDeploymentForOpenShift()`
https://github.com/eclipse/jkube/blob/a2205dc2e90716cd6d715bcacd9fcc569d2dee59/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/DefaultControllerEnricher.java#L121

https://github.com/eclipse/jkube/blob/a2205dc2e90716cd6d715bcacd9fcc569d2dee59/jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/BaseEnricher.java#L218-L220

**Comment by manusa** [comment]
Both configurations should be independent of each other.

This means that if I state `<jkube.enricher.jkube-controller.type>Deployment</jkube.enricher.jkube-controller.type>` the switchToDeployment flag shouldn't be required/needed to be provided in addition to.

The `switchToDeployment` flag seems to be very specific, so probably can be used in specific deployment scenarios where I want to override the standard configuration in a quick way. So IMO, this should take precedence over any other configuration (not so sure about fragments).

**Comment by rohanKanojia** [comment]
If I refactor DefaultControllerEnricher to remove switchToDeployment specific code, I'm still not able to see Deployment being generated. Looks like [DeploymentConfigEnricher](https://github.com/eclipse/jkube/blob/master/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/DeploymentConfigEnricher.java#L57) forcibly converts Deployment to DeploymentConfig on platform mode OpenShift. I'm not sure how one enricher can check how other enricher is configured(without checking property value).

However, if I manually disable DeploymentConfig enricher like this. I'm able to see Deployment getting generated with `<jkube.enricher.jkube-controller.type>Deployment</jkube.enricher.jkube-controller.type>`:
```xml
            <configuration>
              <enricher>
                <excludes>
                  <exclude>jkube-openshift-deploymentconfig</exclude>
                </excludes>
              </enricher>
            </configuration>
```
