### ISSUE TITLE
Quotas for jkube.build.strategy docker

### ISSUE THREAD

**Issue by ochstobi** [eclipse/jkube#639]
### Info

* Eclipse JKube version : 1.1.1
* Maven version (`mvn -v`) : 3.6.1
* Kubernetes / Red Hat OpenShift setup and version : Openshift 4.6

Hello,

I switched from fabric8-maven-plugin to openshift-maven-plugin. The most things are working good.
But I can't find how to handle quotas for local docker builds.

I use this build strategy `<jkube.build.strategy>docker</jkube.build.strategy>`.
In fabric8 I defined quotas like this:
```
<openshiftBuildConfig>
	<requests>
		<cpu>${request_cpu_build}</cpu>
		<memory>${request_memory_build}</memory>
	</requests>
	<limits>
		<cpu>${limit_cpu_build}</cpu>
		<memory>${limit_memory_build}</memory>
	</limits>
</openshiftBuildConfig>
```
In the documentation this section vanished and I don't know how to handle quotas now. How am I supposed to define this?
Thanks in advance.

**Comment by rohanKanojia** [comment]
I checked code and seems like the flag is still there:
https://github.com/eclipse/jkube/blob/85008d4274a9aa6f0d0a047370d8dcb8c696d7ac/jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/ResourceConfig.java#L81

Do you face problems when you provide this configuration to the plugin?

**Comment by rohanKanojia** [comment]
ohk, seems like something is not working as expected.

**Comment by rohanKanojia** [comment]
Looks like `ResourceConfig` is not being passed from AbstractDockerMojo to JKubeServiceHub:

https://github.com/eclipse/jkube/blob/a2205dc2e90716cd6d715bcacd9fcc569d2dee59/kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractDockerMojo.java#L670-L680

It starts working with this one liner change:
```diff
diff --git a/kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractDockerMojo.java b/kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractDockerMojo.java
index da8b0bf8..54915d95 100644
--- a/kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractDockerMojo.java
+++ b/kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractDockerMojo.java
@@ -673,6 +673,7 @@ public abstract class AbstractDockerMojo extends AbstractMojo
                 .forcePull(forcePull)
                 .imagePullManager(getImagePullManager(imagePullPolicy, autoPull))
                 .buildDirectory(project.getBuild().getDirectory())
+                .resourceConfig(resources)
                 .attacher((classifier, destFile) -> {
                     if (destFile.exists()) {
                         projectHelper.attachArtifact(project, "yml", classifier, destFile);

```

**Comment by manusa** [comment]
OK, but what does the resourceConfig have to do with the build configuration??

Not sure why were those configuration parameters added there in the first place.

**Comment by rohanKanojia** [comment]
BuildConfig is a Kubernetes resource. I think ResourceConfig is correct place for it's configuration. `oc:build` creates BuildConfig, Build and ImageStream while running.

**Comment by manusa** [comment]
From a technical low-level perspective, yes build creates a `BuildConfig` which is indeed an **`OpenShift`** resource.

From a functional perspective it doesn't, since this is related to the build process and not to the final resource generation. Personally I think that describing the build limits in a more agnostic way would make more sense, these limits could then be also applied to other build strategies if applicable.

Anyway, we are where we are, so let's keep it here.

There's also a complete lack of documentation about [this feature](http://maven.fabric8.io/#build-openshift) in our repo.

**Comment by rohanKanojia** [comment]
You're right. I'll add documentation for these. However, I noticed there is no documentation available for the entire ResoureConfig class

**Comment by manusa** [comment]
AFAIK That's because it's partially documented for each Enricher (and the reasoning for my previous rant: ResourceConfig is a technical non-functional entity that covers functional cases ---> Enricher configuration).

**Comment by rohanKanojia** [comment]
I think ResourceConfig and enricher configuration are two separate things.

https://github.com/eclipse/jkube/blob/42b268e3b3e4240190af21139d8806446d87ee8e/kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractDockerMojo.java#L313-L320

I can see some documentation for `<configMap>` in `jkube-configmap-file` but apart from that I'm not able to see any documentation

**Comment by manusa** [comment]
The problem is that (as we've discussed many times) there are far too many ways to configure things and for compatibility reasons, we can't remove them. So yes, you also have the `ProcessorConfig` class used to configure Enrichers (mostly now) + the preferred way (seamlessly translates XML into properties).

But basically ResourceConfig is the Java Class used to deserialize the resources field in the ResourceMojo which is then used by Enrichers (too).

So in documentation:
- [ConfigMap](https://www.eclipse.org/jkube/docs/kubernetes-maven-plugin#jkube-configmap-file)
- [Labels and annotations](https://www.eclipse.org/jkube/docs/kubernetes-maven-plugin#resource-labels-annotations)
- [Secrets](https://www.eclipse.org/jkube/docs/kubernetes-maven-plugin#resource-secrets)
- [Miscellaneous](https://www.eclipse.org/jkube/docs/kubernetes-maven-plugin#_xml_configuration)

Missing in documentation ---> a lot.
