### ISSUE TITLE
Infinite Recursive Resource Copying

### ISSUE THREAD

**Issue by Sheldor5** [eclipse/jkube#776]
### Description

I wanted to add JKube to an already big maven project which already is creating/copying all sorts of files/dependencies and the final Dockerfile into the target/ directory, my intention was to move the image pushing from a bash script to this maven plugin so I wanted to simply user JKube to execute the already filtered target/Dockerfile and push the image to our registry.

After adding the following to the pom.xml this plugin was recursivly copying target/docker into itself ... after some seconds I canceled the process and had to manually delete over 26000 levels of subfolders (which took a while under Windows):

```
            <plugin>
                <groupId>org.eclipse.jkube</groupId>
                <artifactId>kubernetes-maven-plugin</artifactId>
                <configuration>
                    <images>
                        <image>
                            <name>someco/myapp:%l</name>
                            <build>
                                <contextDir>${project.build.directory}</contextDir>
                                <dockerFile>Dockerfile</dockerFile>
                            </build>
                        </image>
                    </images>
                </configuration>
            </plugin>
```

### Info

* Eclipse JKube version : 1.3.0
* Maven version (`mvn -v`) : 3.6.3

**Comment by manusa** [comment]
Hi @Sheldor5,

In your current configuration (you are using the [manual External Dockerfile](https://www.eclipse.org/jkube/docs/kubernetes-maven-plugin#external-dockerfile) mode). The first issue I see here is that you are assuming that you Dockefile will be in your `${project.baseDir}/target`, which unless you are running some sort of preassembly, won't be the case (the `<dockerFile>`configuration element expects either a relative path to the provided `<contextDir>` or an absolute path. So probably, once you overcome the recursion problem you'll need to fix this too.

If the only configuration you are providing is for the final image name, then you could switch into the [Simple Dockerfile build mode](https://www.eclipse.org/jkube/docs/kubernetes-maven-plugin#simple-dockerfile-build) by moving your original Dockerfile to the project's root directory and set the image name using the following Maven property `jkube.image.name`. In this case, you won't need to provide any additional `<configuration>` for the plugin (check this [quickstart](https://github.com/eclipse/jkube/tree/773a224e8c415f08beb27c504046369c447d3f36/quickstarts/maven/docker-file-simple) for a working example).

If you are comfortable providing the configuration (like now), then you need to add some exclusions. Create a `.jkube-dockerignore` file and add the entries you consider, such as `docker/**`. You just need to make sure that the `contextDir` value aligns with the rest of provided configurations for the exclusions and the `dockerFile`. This [quickstart](https://github.com/eclipse/jkube/tree/773a224e8c415f08beb27c504046369c447d3f36/quickstarts/maven/docker-file-provided) shows several ways of an extended Dockerfile mode configuration.

Relates to
- #590 
- #693
- #529 
- #567

**Comment by Sheldor5** [comment]
Hi @manusa ,

My maven project is already creating everything needed for the docker build: from compiling java sources to dependency-copying everything and also filtering the Dockerfile is already done by the maven project even without JKube.

Currently we run `mvn clean verify` and `docker build ...` one after another in a bash script, so maven is fully preparing everything in `${project.baseDir}/target` so we just have to `cd ${project.baseDir}/target && docker build ...` .

But JKube is doing some extra magic which results in chaos (from my POV) ...

For me JKube is mixing Maven and Docker conventions and is reinventing the wheel.

How can I use JKube so it simply uses `${project.baseDir}/target` as contextDir (like with Docker) without JKube creating/copying everything into an extra directory under `${project.baseDir}/target/docker/<image_name>/<assembly_name>/build`?

Maven is already doing all the dependency-copy and resource-filtering stuff to fully prepare the `${project.baseDir}/target` so I don't know why JKube is trying to do the exact same thing??

**Comment by manusa** [comment]
> My maven project is already creating everything...

> How can I use JKube so it simply uses...

You are in the scenario I describe in my 3rd paragraph. In this case, if you don't want to add an assembly configuration, you need to create a  `.jkube-dockerignore` file in the context directory, with the necessary entries to avoid recursion (i.e. `docker/**/*`).

If you want to go a further step, you can define your own assembly configuration, and configure your Dockerfile accordingly. Anyway, since this might be more complicated, it would be enough by following the step described in the previous paragraph. If not, we can analyze this step together.

> For me JKube is mixing Maven and Docker conventions and is reinventing the wheel.

This is because you have a very specific scenario where you can't take full advantage of what JKube has to offer. In most cases, providing a Dockerfile is not necessary (especially if you want to mix different build strategies: Jib, S2i, etc.). However, if your project+Dockerfile is not that complicated, you might consider avoiding the use of a Dockerfile altogether.

There are also cases where you don't want to use JKube alongside with Maven (especially now that we are implementing Gradle plugins).

So yes, there are some JKube features that partially collide with what some other Maven plugins do for you. But if you opt to use other plugins, you are forced to configure them too.

> I don't know why JKube is trying to do the exact same thing

JKube is not doing the exact same thing. JKube preassembles any file that is going into the final container image in the .`/target/docker/build` directory. This is because (depending on your build strategy) JKube will create a tar package that will be sent to the docker daemon (local or remote) that will build the image.

**Comment by Sheldor5** [comment]
@manusa thanks again for your answer!

While you say "you have a very specific scenario" I would say "I have the most basic scenario" (just run `docker build .` inside `${project.baseDir}/target`) but it looks like JKube is meant for more complex scenarios :)

Also `contextDir` in Docker means "working directory" while `contextDir` in JKube means "copy everything from there into my own folder structure" so I have to modify the `Dockerfile` to grab dependencies from `COPY ./<assembly_name>/lib/*` instead of `COPY ./lib/*` ... that's what I meant with "mixing conventions and reinventing the wheel" so I got really confused what `contextDir` actually means and does in JKube,

Anyway I got it working with a `.jkube-dockerignore` file ... JKube is now copying everything a second time but OK, let it be.

Can you explain what exactly is the tar file for? because browsing the tar file there is only the Dockerfile inside and nothins else ... but the image is built with all JARs/Files anyway ...

**Comment by manusa** [comment]
If you have a very basic scenario (and a basic Dockerfile -> FROM,LABELS,COPY,ENTRYPOINT), then the easiest way would be to take full advantage of JKube and remove the Dockerfile altogether and configure everything else via JKube.

Your tar file `./target/docker/.../tmp/docker-build.tar` should contain the same files you have in `./target/docker/.../build`. This is what the docker daemon receives in order to perform the build.

Are you using JKube only to build your container images, or are you using it to create your Kubernetes resources too?

**Comment by Sheldor5** [comment]
@manusa currently only to build the Docker Images.

Many thanks for your detailed explainations, I close this because it seems not to be an issue from JKube's POV.
