### ISSUE TITLE
deps: Bump Kubernetes|OpenShift client to 5.10.1 (or latest)

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#802]
### Description

- [x] Bump the KubernetesClient version to latest release (---> 5.10.1 or latest).
- [x] Replace usage of GenericCustomResource with GenericKubernetesResource
- [x] Use the new getApiGroups and getApiResources [instead of CustomResourceDefinitions](https://github.com/eclipse/jkube/blob/4358c2507e8ca3da377cb52264cba2bf6b17a7d2/jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/ApplyService.java#L225) (which may not be available or might be blocked by Cluster Roles) ---> Maybe this was partially addressed when using the resource() DSL method, so might not be necessary to directly access the apiGroups and apiResources endpoints
- [x] Create corresponding CQs

**Comment by maycap123** [comment]
can i try this?

**Comment by maycap123** [comment]
I would like to try this task, if I'm allowed to have several assignments :) if so, I need some further explanation: is there a trick to find out in which pom.xml the soon-to-be changing dependency is? what is to change with "GenericKubernetesResource? And last but not least, what is a cq? :)

**Comment by rohanKanojia** [comment]
It's here
https://github.com/eclipse/jkube/blob/5a1828c0ece30567fdcf89ce7668bb8c2003211d/jkube-kit/parent/pom.xml#L57 

In order to handle CustomResources in a generic way, we introduced [GenericCustomResource](https://github.com/eclipse/jkube/blob/master/jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/GenericCustomResource.java). But in latest releases of Fabric8 Kubernetes Java Client, [GenericKubernetesResource](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/api/model/GenericKubernetesResource.java) got introduced. We need to delete our own version of GenricCustomResource and use GenericKubernetesResource coming from KubernetesClient

You don't need to worry about CQ. It's something that project maintainers have to create whenever they add/upgrade new dependency.

**Comment by maycap123** [comment]
Then please assign me :)

**Comment by maycap123** [comment]
Am I supposed to change only in the given code citation? or throughout ApplyService and ApplyServiceTest.java?

**Comment by rohanKanojia** [comment]
> Am I supposed to change only in the given code citation? or throughout ApplyService and ApplyServiceTest.java?

You're right. You're supposed to replace usages of GenericCustomResource across project. Idea is to get rid of GenericCustomResource and use GenericKubernetesResource from kubernetes java client

**Comment by maycap123** [comment]
Is there a trick to find out in which class GenericCustomResource is used?

**Comment by rohanKanojia** [comment]
You can do a `git grep -in GenericCustomResource` to list all files referencing GenericCustomResource

**Comment by maycap123** [comment]
Thanks, i will do this later and maybe i will issue the pull request then :)

**Comment by maycap123** [comment]
Sorry, I'm still on this, got a lot on my plate right now. Hope that's ok

**Comment by rohanKanojia** [comment]
@maycap123 : Hello, I want to pick this task from where you left. Do you have your branch pushed somewhere? I can cherry-pick your commit and include it in the PR,

**Comment by robinroos** [comment]
5.12.0 is available.  Should that be adopted before jkube 1.6.0 is cut?

**Comment by rohanKanojia** [comment]
@robinroos : Sorry, 1.6.0 is out already

https://repo1.maven.org/maven2/org/eclipse/jkube/openshift-maven-plugin/1.6.0/
https://repo1.maven.org/maven2/org/eclipse/jkube/kubernetes-maven-plugin/1.6.0/

**Comment by manusa** [comment]
> 5.12.0 is available. Should that be adopted before jkube 1.6.0 is cut?

There shouldn't be any notable differences for JKube users between 5.10.1 and 5.12.0.

We'll bump the client version in our next minor release (which shouldn't take as long as this one)
