### ISSUE TITLE
OpenShiftBuildTask: ocBuild Generator - SpringBoot

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#903]
## Description

Child of #31 
Equivalent of #850

ocBuild Gradle task works with SpringBoot Generator.

Make sure that the right artifact is chosen

**Comment by rohanKanojia** [comment]
Does this issue include verifying ocBuild task works okay? Or do you think something needs to be done in OpenShiftBuildTask in regards to SpringBoog generator?

**Comment by manusa** [comment]
Verify that Spring Boot generator behaves OK when using ocBuild with **all** of the available strategies, configurations, flags, etc.

Probably nothing needs to be done, but it must be tested and verified.

Maybe some tests apply.

**Comment by manusa** [comment]
> Make sure that the right artifact is chosen

I had to add a fix for this (#902) https://github.com/eclipse/jkube/commit/ef35f77d4364bc9fe3d5e29718a564b02d01ad1d because the repackage task of the Spring plugin was running after our Build task in some cases. This meant that the plain jar (not uber/fat) was chosen instead.

**Comment by rohanKanojia** [comment]
I've tested openshift-gradle-plugin on `spring-boot`, `spring-boot-crd` and `spring-boot-camel-complete` quickstarts and it seems to be working in S2I and Docker build strategies. Basically I've run the following commands:
```
gradle clean build
gradle ocBuild ocResource ocApply
```
I think right jar is getting picked in all above three cases.

**Comment by manusa** [comment]
Did you test jib?

**Comment by rohanKanojia** [comment]
In order to test jib, I need to implement push task first.

**Comment by manusa** [comment]
Well, this is only about building, not pushing. We are testing that when you build the image using `ocBuild` task, the right image is built (including artifact + file assembly).
I don't understand why would you need the push goal for this. Just build the image and run it locally. I mean, how did you test #850 if we don't have `k8sPush` either??

**Comment by rohanKanojia** [comment]
For Kubernetes, I used minikube and loaded image tarball into minikube's docker daemon. How am I supposed to do the same with OpenShift?

**Comment by manusa** [comment]
You are testing the build process. You only need to test that the final image is OK. When you test the apply process you will have to check if the image+manifest work OK in the cluster.

**Comment by rohanKanojia** [comment]
I've tested JIB build strategy with `spring-boot`, `spring-boot-crd`, `spring-boot-camel-complete` and `spring-boot-with-jib-assembly` and it seems to be working okay for all except `spring-boot-camel-complete`(see #932).

I've tried with various combinations of `build`, `clean` and `ocBuild` tasks and here are my observations:
- `gradle clean` + `gradle ocBuild` -> :x: #931 
- `gradle ocBuild clean` -> :x: Invalid use case; build directory gets deleted after `ocBuild` task
- `gradle ocBuild clean` -> :x:
- `gradle clean build ocBuild` -> :heavy_check_mark:
- `gradle build clean ocBuild` -> :x: #931
- `gradle ocBuild clean build` -> :x: Invalid use case; build directory gets deleted after `ocBuild` task
- `gradle build ocBuild` -> :heavy_check_mark:
- `gradle ocBuild build` -> :heavy_check_mark:

I had also checked precedence order of `ocBuild` goal when run along with `ocResource` and `ocApply goals:

- `gradle ocBuild ocResource ocApply`: `ocBuild` -> `ocResource` -> `ocApply`
- `gradle ocBuild ocApply ocResource`: `ocBuild` -> `ocResource` -> `ocApply`
- `gradle ocResource ocBuild ocApply`: `ocResource` -> `ocBuild` -> `ocApply`
- `gradle ocResource ocApply ocBuild`: `ocResource` -> `ocApply` -> `ocBuild`
- `gradle ocApply ocBuild ocResource`: `ocResource` -> `ocApply` -> `ocBuild`
- `gradle ocApply ocResource ocBuild`: `ocResource` -> `ocApply` -> `ocBuild`

I've discussed this with Marc whether it makes sense to have `ocBuild` precede over `ocResource` when executed together but we've decided not to do it since resources can be created later as well.
